import { defineConfig } from "vitepress";

export default defineConfig({
  title: "AgentAgora",
  description: "The open layer for agent identity, discovery, settlement, and audit.",
  cleanUrls: true,
  lastUpdated: true,
  // The TypeDoc-generated SDK reference under /sdk-reference/ is produced by
  // `pnpm typedoc` (see package.json). When running `vitepress dev/build`
  // before typedoc has materialized the directory, those links are
  // legitimately dead — ignore them rather than failing the build.
  ignoreDeadLinks: [/^\/sdk-reference\//],
  themeConfig: {
    siteTitle: "AgentAgora",
    nav: [
      { text: "Introduction", link: "/intro" },
      { text: "Quickstart", link: "/quickstart" },
      { text: "Protocol (AAP)", link: "/protocol" },
      { text: "GitHub", link: "https://github.com/agentagora/agentagora" },
    ],
    sidebar: [
      {
        text: "Get started",
        items: [
          { text: "Introduction", link: "/intro" },
          { text: "Quickstart", link: "/quickstart" },
        ],
      },
      {
        text: "Concepts",
        items: [
          { text: "AID", link: "/concepts/aid" },
          { text: "Manifest", link: "/concepts/manifest" },
          { text: "Audit chain", link: "/concepts/audit" },
          { text: "Disputes", link: "/concepts/disputes" },
        ],
      },
      {
        text: "Reference",
        items: [
          { text: "Protocol (AAP)", link: "/protocol" },
          {
            text: "SDK reference",
            link: "/sdk",
            collapsed: true,
            items: [
              // Generated by TypeDoc from packages/sdk/src/index.ts at build
              // time. The directory is gitignored; if it's missing locally,
              // run `pnpm --filter @agentagora/docs typedoc` to materialize
              // it. VitePress will warn (not fail) on a missing link target.
              { text: "API index (generated)", link: "/sdk-reference/" },
            ],
          },
          { text: "Cloud API reference", link: "/cloud-api" },
          { text: "Self-host", link: "/self-host" },
        ],
      },
    ],
    socialLinks: [{ icon: "github", link: "https://github.com/agentagora/agentagora" }],
    search: {
      provider: "local",
    },
    editLink: {
      pattern: "https://github.com/agentagora/agentagora/edit/main/apps/docs/:path",
      text: "Edit this page on GitHub",
    },
    footer: {
      message: "Released under the Apache-2.0 License.",
      copyright: "Copyright (c) 2026 AgentAgora contributors",
    },
  },
});
